### ISSUE TITLE
Opening screen

### ISSUE THREAD

**Issue by CarmenZak** [SchoolOfCode/week-1-hackathon-3cs#8]
```[tasklist]
### Tasks
- [x] Add a draft title or issue reference here
- [x] Pop up with player instructions - CB
- [x] start button - CB
- [x] countdown timer- CZ
```
Player instructions
start button
countdown timer
- [ ] Add a draft title or issue reference here
```
