### ISSUE TITLE
Room 1 Game Screen

### ISSUE THREAD

**Issue by CarmenZak** [SchoolOfCode/week-1-hackathon-3cs#9]
Room 1 tasks
- [x] riddle note sprite that appears when bat clicked - CL
- [x] flying bat: random movement around until clicked, then move to position at side of screen - CL
- [x] countdown - CZ
- [x] find riddle - cz
- [x] key animation - hide at start, appear when clicked, disappear after 5 secs - CZ
- [x] door opening - creaky door sound and black shape over door frame - CB
- [ ] exit room transition
- [ ] extra sprites - cl/cb/cz

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```
